### ISSUE TITLE
Proposal Feeback

### ISSUE THREAD

**Issue by aplarson** [dcurletti/Tweheat#1]
My comments:
1. You mention that you don't plan on having a database for the MVP, but that there are some bonus features that might require it; I would consider shuffling features to involve some database work in the main project phase, depending on what features you are considering.
2. Unless you're extremely comfortable with Node, I'd stick with Rails for the initial build; you can always swap backends later if you have the time and motivation
3. I'm not thrilled with having a "styling phase"; in my experience, styling is best tackled in smaller chunks as the project progresses.

**Comment by dcurletti** [comment]
Hey Andrew- Thanks for the comments.  

1. I actually don't foresee myself needing a database, even if I do get to the bonus features- I merely wrote that because I thought it would be frowned upon if I didn't have one.  

2. Okay cool. 

3.  Sounds good, I will refactor my phases later tonight to reflect that.

**Comment by aplarson** [comment]
I think that you're going to find that this project doesn't have enough complexity for a final project. I'd like to see you move "replay mode" from the bonus into your main project, allowing users to record activity and then play it back at different speeds.

**Comment by dcurletti** [comment]
Ok cool- I will add some bonus features to the MVP.
